In [ ]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv('spam.csv', encoding='latin-1')
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [ ]:
df=df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis='columns')

In [ ]:
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
df['spam']=df['v1'].apply(lambda x: 1 if x=='spam' else 0)
df

v1                                                 v2  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
...    ...                                                ...   ...
5567  spam  This is the 2nd time we have tried 2 contact u...     1
5568   ham              Will Ì_ b going to esplanade fr home?     0
5569   ham  Pity, * was in mood for that. So...any other s...     0
5570   ham  The guy did some bitching but I acted like i'd...     0
5571   ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df.v2,df.spam,test_size=0.2)

In [ ]:
x_train.shape

(4457,)

In [ ]:
y_train.shape

(4457,)

In [ ]:
x_test.shape

(1115,)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vector=CountVectorizer()

In [ ]:
x_train_v=vector.fit_transform(x_train.values)
x_train_v

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58877 stored elements and shape (4457, 7709)>

In [ ]:
x_train_v.shape

(4457, 7709)

In [ ]:
dir(vector)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_r

In [ ]:
vector.vocabulary_

{'geeee': 3105,
 'miss': 4474,
 'you': 7660,
 'already': 929,
 'know': 3945,
 'your': 7664,
 'all': 919,
 'can': 1639,
 'think': 6796,
 'about': 766,
 'fuck': 3036,
 'wait': 7300,
 'till': 6852,
 'next': 4723,
 'year': 7633,
 'when': 7433,
 'we': 7367,
 'will': 7470,
 'be': 1277,
 'together': 6895,
 'loving': 4211,
 'kiss': 3933,
 'how': 3522,
 'much': 4595,
 'would': 7561,
 'it': 3751,
 'cost': 2034,
 'to': 6885,
 'hire': 3442,
 'hitman': 3447,
 'today': 6891,
 'is': 3740,
 'song': 6258,
 'dedicated': 2223,
 'day': 2192,
 'which': 7443,
 'dedicate': 2222,
 'for': 2948,
 'me': 4376,
 'send': 5957,
 'this': 6805,
 'ur': 7154,
 'valuable': 7200,
 'frnds': 3022,
 'but': 1582,
 'first': 2876,
 'rply': 5785,
 'heart': 3382,
 'empty': 2591,
 'without': 7503,
 'love': 4201,
 'mind': 4453,
 'wisdom': 7489,
 'eyes': 2749,
 'dreams': 2457,
 'amp': 956,
 'life': 4077,
 'so': 6228,
 'alwys': 940,
 'in': 3635,
 'touch': 6944,
 'good': 3187,
 'night': 4734,
 'sweet': 6606,
 'ps': 5425,
 'no': 4753,


In [ ]:
x_train_np=x_train_v.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
import numpy as np
np.where(x_train_np[0]!=0)

(array([ 766,  919,  929, 1277, 1639, 3036, 3105, 3933, 3945, 4211, 4474,
        4723, 6796, 6852, 6895, 7300, 7367, 7433, 7470, 7633, 7660, 7664]),)

In [ ]:
x_train[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_v,y_train)

MultinomialNB()

In [ ]:
x_test_v=vector.transform(x_test)
x_test_v

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 14006 stored elements and shape (1115, 7709)>

In [ ]:
y_pred=model.predict(x_test_v)
y_pred

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       962
           1       0.96      0.93      0.94       153

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
sms=[
    'hey can we get together to watch footbal game tomorrow',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward'
]

In [ ]:
sms_numerical=vector.transform(sms)
predictions=model.predict(sms_numerical)

In [ ]:
for prediction in predictions:
    if prediction==1:
        print('spam')
    else:
        print('ham')

ham
spam
